### ISSUE TITLE
可以支持bungeecord吗，感谢

### ISSUE THREAD

**Issue by PTPAAA** [handy-git/ip2region#3]

**Comment by handy-git** [comment]
如果你在BC的config.yml里开启了ip-forward
那么你必须在子端的spigot.yml里开启bungeecord: true
如果不开启ip-forward，那么子端检测到的玩家IP都会是127.0.0.1
如果开启ip-forward，那么子端检测到的玩家会是正确的IP

温馨提示；倘若开启bungeecord，最好将server.propres中的server-ip改为BC IP（如127.0.0.1）
防止其他玩家通过自建BC绕过BC登入子端
