### ISSUE TITLE
给驯服的狗命名会显示主人的IP地址

### ISSUE THREAD

**Issue by yinengbei** [handy-git/ip2region#6]
![image](https://github.com/user-attachments/assets/9be5e03e-aa84-4d46-b77e-68c6b8807c74)

**Comment by handy-git** [comment]
本插件只提供变量功能的，不会影响别的。
你这个情况应该是用其他插件给玩家添加了 **头顶变量**   这功能会同步到自己驯服的生物上(原版特性)
